In [1]:
import pandas as pd

## Data

In [3]:
df = pd.read_csv('C:/Users/Ryan Bobby A/Documents/RWTH AACHEN/KULIAH/THESIS_BISMILLAH/Exercise NLP/ex_krishnaik/fake-news/train.csv')

In [4]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

## Clean Dataset

In [8]:
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[20800 rows x 5 columns]

In [5]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [9]:
df = df.dropna()

In [10]:
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[18285 rows x 5 columns]

## Independent - Dependent Features

In [11]:
X=df.drop('label', axis=1)

In [12]:
y=df['label']

In [13]:
X.shape

(18285, 4)

In [14]:
y.shape

(18285,)

## NLP

In [15]:
import tensorflow as tf

In [16]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [17]:
#Vocabulary size
voc_size = 5000

In [18]:
messages=X.copy()

In [19]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [20]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [21]:
messages.reset_index(inplace=True)

In [22]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [23]:
import nltk
import re
from nltk.corpus import stopwords

In [24]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Ryan Bobby
[nltk_data]     A\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

## Data Pre-Processing (Stemming, Stopwords)

In [28]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [29]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

## OHE Representation

In [30]:
onehot_repr = [one_hot(words, voc_size) for words in corpus]
onehot_repr

[[32, 2955, 3443, 2603, 639, 4367, 803, 3455, 1994, 965],
 [3141, 2153, 1115, 2616, 4083, 4817, 551],
 [124, 569, 4475, 650],
 [1375, 718, 70, 4771, 3887, 4973],
 [299, 4083, 4500, 3949, 112, 4556, 4083, 4515, 1619, 4268],
 [2451,
  3346,
  723,
  4969,
  777,
  1630,
  931,
  2079,
  4440,
  3343,
  4931,
  3664,
  3296,
  3181,
  551],
 [2109, 4700, 1197, 4454, 2246, 4164, 1969, 2622, 4311, 4718, 2078],
 [1366, 303, 1367, 1569, 4974, 3991, 1630, 2198, 4311, 4718, 2078],
 [1552, 2638, 1964, 28, 1084, 4667, 2161, 3550, 1630, 4858],
 [3458, 3988, 4357, 2362, 3291, 4234, 1169, 733],
 [3056, 381, 2592, 494, 3709, 4602, 1974, 4664, 85, 1789, 3495],
 [4771, 742, 639, 4667, 1630, 4974],
 [4133, 1920, 4359, 1640, 1309, 29, 497, 3977, 1141],
 [4975, 2148, 968, 4242, 1688, 4298, 3471, 4311, 4718, 2078],
 [3513, 3948, 3565, 3915, 367, 4311, 4718, 2078],
 [4943, 4609, 4365, 2725, 814, 3552, 3424, 1170, 4536, 1865],
 [4342, 4842, 2153],
 [4467, 2565, 1616, 2000, 1630, 4976, 4080, 551],
 [4563, 179

In [31]:
onehot_repr[2]

[124, 569, 4475, 650]

In [33]:
corpus[2]

'truth might get fire'

## Add Padding

In [34]:
sent_length = 20
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 3455 1994  965]
 [   0    0    0 ... 4083 4817  551]
 [   0    0    0 ...  569 4475  650]
 ...
 [   0    0    0 ... 4311 4718 2078]
 [   0    0    0 ...  574 4259 1813]
 [   0    0    0 ...  258 2527 4796]]


## OHE to Vector + Model

In [71]:
embedding_vector_features=40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length = sent_length))
model.add(LSTM(100)) #LSTM with 100 neurons
model.add(Dense(1, activation = 'sigmoid')) #Our Output is 1 because its binary, and also activation of sigmoid
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_3 (LSTM)               (None, 100)               56400     
                                                                 
 dense_3 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [72]:
y_final

array([1, 0, 1, ..., 0, 1, 1], dtype=int64)

In [73]:
len(embedded_docs), y.shape

(18285, (18285,))

In [74]:
import numpy as np

In [75]:
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [76]:
X_final.shape, y_final.shape

((18285, 20), (18285,))

## Model Training

In [77]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [78]:
model.fit(X_train, y_train, validation_data = (X_test, y_test), epochs=10, batch_size=6)

Epoch 1/10
2042/2042 [==============================] - 13s 6ms/step - loss: 0.2267 - accuracy: 0.9035 - val_loss: 0.1923 - val_accuracy: 0.9153
Epoch 2/10
2042/2042 [==============================] - 11s 6ms/step - loss: 0.1306 - accuracy: 0.9470 - val_loss: 0.1942 - val_accuracy: 0.9200
Epoch 3/10
2042/2042 [==============================] - 11s 6ms/step - loss: 0.0878 - accuracy: 0.9666 - val_loss: 0.2237 - val_accuracy: 0.9175
Epoch 4/10
2042/2042 [==============================] - 11s 6ms/step - loss: 0.0511 - accuracy: 0.9815 - val_loss: 0.2743 - val_accuracy: 0.9122
Epoch 5/10
2042/2042 [==============================] - 11s 6ms/step - loss: 0.0242 - accuracy: 0.9927 - val_loss: 0.3450 - val_accuracy: 0.9085
Epoch 6/10
2042/2042 [==============================] - 11s 6ms/step - loss: 0.0160 - accuracy: 0.9953 - val_loss: 0.4328 - val_accuracy: 0.9128
Epoch 7/10
2042/2042 [==============================] - 11s 5ms/step - loss: 0.0087 - accuracy: 0.9976 - val_loss: 0.4918 - val_ac

## Performance Metrics And Accuracy

In [49]:
y_pred=model.predict(X_test)

189/189 [==============================] - 3s 2ms/step


In [50]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [51]:
from sklearn.metrics import confusion_matrix

In [52]:
confusion_matrix(y_test,y_pred)

array([[3138,  281],
       [ 246, 2370]], dtype=int64)

In [53]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9126760563380282

In [54]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.92      0.92      3419
           1       0.89      0.91      0.90      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035



## Adding Dropout

In [55]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3)) #After Embedding Layer, we can use dropout 30% of the neuron
model.add(LSTM(100))
model.add(Dropout(0.3)) #After LSTM, we can use dropout 30% of the neuron
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

## Model Training after Dropout (to avoid over-fitting)

In [56]:
model.fit(X_train, y_train, validation_data = (X_test, y_test), epochs=10, batch_size=6)

Epoch 1/10
2042/2042 [==============================] - 13s 6ms/step - loss: 0.2315 - accuracy: 0.8975 - val_loss: 0.1886 - val_accuracy: 0.9168
Epoch 2/10
2042/2042 [==============================] - 11s 5ms/step - loss: 0.1355 - accuracy: 0.9473 - val_loss: 0.1987 - val_accuracy: 0.9188
Epoch 3/10
2042/2042 [==============================] - 11s 5ms/step - loss: 0.0943 - accuracy: 0.9655 - val_loss: 0.1967 - val_accuracy: 0.9191
Epoch 4/10
2042/2042 [==============================] - 11s 6ms/step - loss: 0.0664 - accuracy: 0.9759 - val_loss: 0.2377 - val_accuracy: 0.9128
Epoch 5/10
2042/2042 [==============================] - 11s 6ms/step - loss: 0.0426 - accuracy: 0.9854 - val_loss: 0.3013 - val_accuracy: 0.9175
Epoch 6/10
2042/2042 [==============================] - 12s 6ms/step - loss: 0.0283 - accuracy: 0.9904 - val_loss: 0.3335 - val_accuracy: 0.9137
Epoch 7/10
2042/2042 [==============================] - 12s 6ms/step - loss: 0.0214 - accuracy: 0.9929 - val_loss: 0.4037 - val_ac

In [57]:
y_pred=model.predict(X_test)

189/189 [==============================] - 1s 2ms/step


In [58]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [59]:
from sklearn.metrics import confusion_matrix

In [60]:
confusion_matrix(y_test,y_pred)

array([[3118,  301],
       [ 233, 2383]], dtype=int64)

In [61]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9115161557580779

In [62]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.91      0.92      3419
           1       0.89      0.91      0.90      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035

