# Needed Modules

In [49]:
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
import matplotlib.patches as mpatches

In [1]:
# from huggingface_hub import notebook_login
# from huggingface_hub import upload_file
# from huggingface_hub import delete_file
# from huggingface_hub import Repository
# notebook_login()

# Import Fine-Tuned GeoBERT

In [4]:
from transformers import TFAutoModelForTokenClassification, TFAutoModelForSequenceClassification
from transformers import AutoTokenizer
model_checkpoint = "botryan96/GeoBERT_analyzer"

tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)
models = TFAutoModelForSequenceClassification.from_pretrained(model_checkpoint)

Downloading:   0%|          | 0.00/373 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/201k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/599k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/125 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/737 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some layers from the model checkpoint at botryan96/GeoBERT_analyzer were not used when initializing TFBertForSequenceClassification: ['dropout_75']
- This IS expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertForSequenceClassification were initialized from the model checkpoint at botryan96/GeoBERT_analyzer.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


# Data Preparation

In [94]:
sentence1 = ['The green energy problem has been a lovely issue in America and Europe.']
sentence2 = ['Ryan works for some energy industries in America while his love is in Europe.']

In [95]:
outputs1 = tokenizer(sentence1, return_tensors="np", padding="longest")
out1 = models(outputs1, output_hidden_states= True)

outputs2 = tokenizer(sentence2, return_tensors="np", padding="longest")
out2 = models(outputs2, output_hidden_states= True)

In [96]:
loc = outputs1.word_ids()
tokens = outputs1.tokens()
ids = tokenizer.convert_tokens_to_ids(tokens)

print(list(zip(tokens, ids, loc)))
print(' ')

[('[CLS]', 2, None), ('the', 106, 0), ('green', 1699, 1), ('energy', 3726, 2), ('problem', 5844, 3), ('has', 433, 4), ('been', 371, 5), ('a', 23, 6), ('lo', 2882, 7), ('##vel', 540, 7), ('##y', 70, 7), ('issue', 7789, 8), ('in', 117, 9), ('america', 7769, 10), ('and', 119, 11), ('europe', 4243, 12), ('.', 11, 13), ('[SEP]', 3, None)]
 


In [97]:
loc = outputs2.word_ids()
tokens = outputs2.tokens()
ids = tokenizer.convert_tokens_to_ids(tokens)

print(list(zip(tokens, ids, loc)))
print(' ')

[('[CLS]', 2, None), ('ryan', 12315, 0), ('works', 10548, 1), ('for', 162, 2), ('some', 528, 3), ('energy', 3726, 4), ('industries', 10832, 5), ('in', 117, 6), ('america', 7769, 7), ('while', 2453, 8), ('his', 5030, 9), ('lo', 2882, 10), ('##ve', 147, 10), ('is', 151, 11), ('in', 117, 12), ('europe', 4243, 13), ('.', 11, 14), ('[SEP]', 3, None)]
 


In [98]:
tes1 = out1.hidden_states[-1][0]
tes1
col1 = [i for i in range(len(tes1[0]))]
lst1 = tes1.numpy().tolist()
df1 = pd.DataFrame(lst1, columns = col1, dtype = float)
df1

0         1         2         3         4         5         6    \
0   0.526861  1.708692  1.125218  0.103458  0.517974  1.270152 -0.889633   
1   0.559776  0.986373  1.370549 -1.002640 -1.597162  1.568433  0.742627   
2   0.409344  2.308864  0.781421 -0.959297 -0.932325  0.570019  0.231656   
3  -0.805968  0.445693 -0.212789 -1.490984  0.074572 -1.259386  0.501055   
4  -1.431995  1.711769 -0.183973 -0.949505 -0.300466  0.790710  0.316157   
5  -0.207164  1.223704  0.426163 -1.400387 -0.607666  0.571201 -1.492018   
6  -0.083866  0.458309  0.257573 -1.050743  0.223076  0.126370 -1.146976   
7   0.763458  0.389486  1.744185 -0.179043 -1.066321  1.421597 -0.219950   
8   0.592406  1.193478  0.786389 -0.491592 -0.984515  0.672686  0.375335   
9   0.349862  1.422941  0.590019 -0.701456 -0.902058  0.620555 -0.594303   
10 -1.236099  0.712626  0.285499 -0.902398 -1.118129  1.242716 -0.259022   
11  0.101556  1.643519 -0.648911 -1.308519 -0.879471 -0.282758 -0.155294   
12  0.190998  0.075285  0.842459 -1.121139 -0.140402  0.912183  0.357731   
13 -4.014646  0.068581  0.166223 -0.857617  1.168605  0.676625  0.361103   
14 -0.381955 -0.699867  0.275741 -1.277321  1.325063  0.574288 -0.056110   
15 -1.864428 -0.778002 -0.410743  0.626503  1.203828  1.102250 -0.449734   
16 -0.498340  1.246815  1.564902 -1.722047 -0.541979  0.611590 -0.490952   
17  0.527959  1.711274  1.126205  0.103550  0.516530  1.268527 -0.888360   

         7         8         9    ...       758       759       760       761  \
0  -2.128117 -0.580222 -1.673796  ...  0.073119  1.389552  1.134918 -0.371036   
1  -1.742769 -0.341264 -1.858063  ... -0.155558  1.190248  2.238168  0.641926   
2  -1.689713 -0.792942 -0.781275  ...  0.805858  1.237293  1.530544 -0.793038   
3   0.463613  0.342775 -1.467355  ... -0.124837  0.343094  0.325841  0.111106   
4  -0.895452 -0.380088 -2.066049  ...  0.831755  0.739650  0.474811 -0.653361   
5  -0.940277 -0.850535 -1.555445  ...  0.309610  0.813578  1.731485 -0.188817   
6  -0.785626 -0.371213 -1.675178  ... -0.136472  1.452729  0.790580  0.364804   
7  -1.490874 -0.695673 -0.420442  ... -0.866535 -0.116628  0.162466  0.862676   
8  -1.778849 -1.276158 -1.765607  ...  0.281838  0.008337  1.107081  0.161767   
9  -0.569866 -1.039921 -0.772726  ...  0.666599  0.910157  1.329038 -0.076275   
10 -0.081512 -1.563170  0.966264  ... -0.087039  0.035628  0.466549  0.568241   
11 -0.454649 -0.282518 -1.371311  ... -0.005217  1.497737  1.160396  0.307404   
12 -0.934881 -1.161863  0.077807  ...  0.250521 -1.277966  0.788262  0.281457   
13 -0.213814 -0.315835 -0.793931  ...  0.874034 -0.900848 -0.285532 -0.543820   
14 -0.500575  0.004458 -1.901048  ...  1.186924 -0.015133 -0.723949 -0.345752   
15 -0.325245 -0.963876  0.899814  ...  0.192963 -0.209136  0.307737  0.333128   
16 -1.527773 -0.686935 -0.562250  ...  0.233103  0.186594  1.267455 -0.246788   
17 -2.128147 -0.580738 -1.674635  ...  0.073716  1.389122  1.133775 -0.372327   

         762       763       764       765       766       767  
0  -1.545351 -1.282610 -0.825831 -0.855169 -1.406805 -1.271665  
1  -1.556880 -0.419763  0.117314  0.887583 -1.074012 -1.450861  
2  -0.904950  0.379752 -0.518825 -0.459834 -1.784434 -0.374684  
3   0.121279 -0.805288  0.629488 -1.848197 -0.311849 -0.144681  
4   0.021514  0.134313 -0.018569  1.146340 -0.654342 -0.504749  
5   0.025634 -0.096194  0.246613 -0.588939 -2.394382 -0.831336  
6  -0.507634 -0.507099  1.319732 -1.725207 -1.300440 -0.171617  
7  -0.747668 -0.329397  1.090864  0.771885 -1.025625 -1.187392  
8  -1.362094  0.651170  0.249711 -1.055596 -0.919503 -0.836657  
9  -0.852221 -0.054070  0.529129 -1.047296 -0.774852 -1.503151  
10 -0.026579  0.598255 -0.246396 -0.428265 -0.579971 -0.732815  
11  0.247998 -0.227863  0.768281 -0.353089 -1.140709 -0.976337  
12 -0.280287  0.692167 -0.062017  0.470579 -0.944876 -1.683712  
13  0.633764 -0.751763 -0.186770  1.182535  0.137821 -0.669310  
14 -1.481813 -1.648365  0.773445 -0.445733 -1.604

In [99]:
tes2 = out2.hidden_states[-1][0]
tes2
col2 = [i for i in range(len(tes2[0]))]
lst2 = tes2.numpy().tolist()
df2  = pd.DataFrame(lst2, columns = col2, dtype = float)
df2

0         1         2         3         4         5         6    \
0   1.317990  1.303441  0.508046 -1.012868 -0.814912 -0.211947  0.050318   
1  -0.126120  0.945822  0.817309 -0.901786 -1.281811  0.577872 -0.575280   
2  -2.060981  1.468702  0.081903 -1.299391 -0.236358  0.832565  1.265005   
3  -0.029254  0.709929  0.950618 -1.347424 -0.724877  0.702199  0.681385   
4   0.076310  1.766653  0.984876 -1.496902 -1.042032  1.379063  0.360621   
5  -0.745638  0.711231 -0.281942 -1.798130 -0.771951 -0.918206  0.498169   
6  -0.544005  0.348523  1.406909 -0.797408 -0.356304 -0.000500  0.974728   
7   0.381857  0.172362  0.782374 -1.815053 -0.463437  0.876038  0.575691   
8  -2.821207  0.352931 -0.118718 -0.465304  0.224041  1.018965 -0.259254   
9  -0.134119  1.984342  0.281666 -0.231477 -0.527362 -0.039399  0.666419   
10  0.271927  0.960269 -0.049040 -1.520713 -0.680346  0.294648  0.002294   
11  0.609344  0.973469  0.503400 -0.509826 -1.411034  0.392860  0.900377   
12  0.803762  1.285418  1.550289 -1.971392 -0.270372  0.737639 -0.601054   
13 -0.357430  0.891017  1.045241 -1.914756 -0.284859  1.236379 -0.125408   
14  0.355184  0.823386  0.973849 -1.674555 -0.713308  1.083930  0.645004   
15 -1.115964 -0.984166 -0.646443  0.274732  0.800367  0.621730 -0.160720   
16 -0.213031  0.930683  1.569853 -2.091389 -0.632309  0.988873  0.009907   
17  1.317671  1.303303  0.508604 -1.014826 -0.816494 -0.217094  0.050833   

         7         8         9    ...       758       759       760       761  \
0   0.396978 -0.099615  0.913923  ...  0.383212 -0.507406  0.542911  0.377075   
1  -1.144387 -0.937899 -0.428756  ...  0.292237 -0.284725  0.838840  0.008309   
2   0.272433 -0.407072  0.295295  ...  1.587976  0.177375  0.981494  0.448281   
3  -1.035072 -1.310820 -0.078759  ...  0.305372 -0.014974  1.563137 -0.345107   
4  -0.997997 -1.226498 -0.502149  ... -0.276422 -0.301983  1.532265  0.394213   
5   0.236460 -0.539661  0.234051  ...  0.460944  0.040657 -0.412405  0.505739   
6  -0.926920 -0.564035 -1.839472  ...  0.027140 -1.101458  0.628224  0.723604   
7  -0.772793 -1.160844 -0.595242  ... -0.169051 -1.440793  0.589112  0.175402   
8   0.601721 -0.545098 -0.627180  ...  0.730058 -1.207904 -0.321726 -0.111557   
9  -1.748122 -0.672592 -1.471874  ...  0.798719  1.204593  1.351075 -0.121728   
10 -1.817284 -0.936888  0.059817  ...  0.317987  0.085807  1.525426 -0.061657   
11 -0.845191 -1.163091  0.202764  ... -0.472324 -1.266016  0.784361  0.197742   
12 -0.390564 -0.003222 -0.447014  ... -0.211643 -0.744756  0.717771  0.105404   
13 -0.701171 -1.362634 -0.846712  ... -0.526000 -0.922846  1.160070 -0.102501   
14 -0.779031 -1.524361 -0.356937  ... -0.370003 -0.941718  1.079820  0.473571   
15  0.703575 -0.300418  1.128020  ... -0.034164 -1.262458 -0.297856  0.342443   
16 -1.122099 -0.826961 -0.032066  ...  0.296765 -0.410679  1.181830 -0.184290   
17  0.397725 -0.099733  0.913900  ...  0.384621 -0.509028  0.540339  0.377194   

         762       763       764       765       766       767  
0  -0.498669  1.202264  0.553271 -0.423616 -0.584370 -1.178537  
1  -0.901890  0.849643  0.265553 -0.845185 -1.602575 -1.482636  
2   0.715820  0.256130  0.031214  0.344961 -0.710749 -0.391703  
3  -0.189799  0.456455  0.197201  0.754403 -1.728047 -1.303501  
4  -0.337609  0.880133  0.477662  0.391227 -1.292357 -1.100600  
5   0.203581  0.545334  0.462181 -0.702651 -0.041726  0.058779  
6   0.642250  0.667115  1.065796 -0.405096 -0.666210 -0.661841  
7  -0.316117  1.461917 -0.020055  0.985393 -0.653783 -1.489531  
8   0.984355 -0.710246  0.453786  1.451899  0.476924  0.079689  
9  -0.486702  0.161823  0.437470 -0.140334 -0.268765 -1.459773  
10  0.150230  0.039194 -0.226751 -0.208504 -0.534297 -1.276796  
11 -0.335252  2.149464  0.818787  1.289777 -0.482486 -0.623047  
12 -0.699962  1.432139 -0.085799  0.152026 -0.799106 -0.910520  
13 -1.117152  1.021720  1.205781  0.139732 -1.309254 -1.594996  
14 -0.698882  1.506651  0.511491  0.268805 -1.073

# Application of PCA

In [121]:
#PCA (Principal Component Analysis) for Entity Word-Level
pca = PCA(n_components=1)
pca.fit(df1)
x_pca = pca.transform(df1)
print('Dimension Before PCA:',df1.shape,'\n''Dimension After PCA:',x_pca.shape)
x_pca

Dimension Before PCA: (18, 768) 
Dimension After PCA: (18, 1)


array([[ -9.56115624],
       [ -6.19110995],
       [ -5.65536481],
       [ -4.3998992 ],
       [ -3.34260658],
       [ -4.34299499],
       [ -7.84049956],
       [  1.79587812],
       [-10.05822841],
       [  0.53559049],
       [ 11.4499833 ],
       [  3.332994  ],
       [  5.40590355],
       [ 14.81978099],
       [ -2.35781587],
       [ 23.52525846],
       [  2.45149502],
       [ -9.56720834]])

In [150]:
#PCA (Principal Component Analysis) for Sequence-Level
pca = PCA(n_components=1)
pca.fit(x_pca.reshape(1,18)*10)
x_pcaa = pca.transform(x_pca.reshape(1,18))
print('Dimension Before PCA:',df1.shape,'\n''Dimension After PCA:',x_pca.shape)
x_pcaa

Dimension Before PCA: (18, 768) 
Dimension After PCA: (18, 1)


C:\Users\Admin\anaconda3\lib\site-packages\sklearn\decomposition\_pca.py:499: RuntimeWarning:

invalid value encountered in true_divide



array([[86.05040616]])

In [151]:
#PCA (Principal Component Analysis) for Sequence-Level
pca = PCA(n_components=1)
pca.fit(x_pca2.reshape(1,18)*10)
x_pcaa = pca.transform(x_pca2.reshape(1,18))
print('Dimension Before PCA:',df1.shape,'\n''Dimension After PCA:',x_pca.shape)
x_pcaa

Dimension Before PCA: (18, 768) 
Dimension After PCA: (18, 1)


C:\Users\Admin\anaconda3\lib\site-packages\sklearn\decomposition\_pca.py:499: RuntimeWarning:

invalid value encountered in true_divide



array([[-74.29408186]])

In [134]:
ener1 = x_pca[3]
amer1 = x_pca[13]
europe1 = x_pca[15]

In [ ]:
siap1 = {'Variable 1':x_pca[:,0],'Variable 2':x_pca[:,1], 'Variable 3':x_pca[:,2],'Topic':1}
df1_pca = pd.DataFrame(data=siap1, columns=['Variable 1','Variable 2','Variable 3','Topic'])
df1_pca

In [110]:
siap1 = {'Variable 1':x_pca[:,0],'Variable 2':x_pca[:,1],'Topic':1}
df1_pca = pd.DataFrame(data=siap1, columns=['Variable 1','Variable 2','Topic'])

In [123]:
siap1 = {'Variable 1':x_pca[:,0], 'Topic':1}
df1_pca = pd.DataFrame(data=siap1, columns=['Variable 1','Topic'])
df1_pca

Variable 1  Topic
0    -9.561156      1
1    -6.191110      1
2    -5.655365      1
3    -4.399899      1
4    -3.342607      1
5    -4.342995      1
6    -7.840500      1
7     1.795878      1
8   -10.058228      1
9     0.535590      1
10   11.449983      1
11    3.332994      1
12    5.405904      1
13   14.819781      1
14   -2.357816      1
15   23.525258      1
16    2.451495      1
17   -9.567208      1

In [135]:
#PCA (Principal Component Analysis) for Entity Word-Level
pca = PCA(n_components=1)
pca.fit(df2)
x_pca2 = pca.transform(df2)
print('Dimension Before PCA:',df2.shape,'\n''Dimension After PCA:',x_pca2.shape)
x_pca2

Dimension Before PCA: (18, 768) 
Dimension After PCA: (18, 1)


array([[ 8.25489798],
       [ 2.71200596],
       [-6.25198875],
       [-7.31118651],
       [-4.46806705],
       [ 2.08382068],
       [-0.50758695],
       [-6.31914621],
       [17.17212384],
       [-7.04977253],
       [-2.09039812],
       [-4.27600973],
       [-2.84005302],
       [-6.61171339],
       [-7.98278371],
       [22.52454036],
       [-5.30315669],
       [ 8.26447384]])

In [136]:
ener2 = x_pca2[5]
amer2 = x_pca2[8]
europe2 = x_pca2[15]

In [137]:
print(ener1, ener2)
print(amer1, amer2)
print(europe1, europe2)

[-4.3998992] [2.08382068]
[14.81978099] [17.17212384]
[23.52525846] [22.52454036]
